---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
  name: appmesh-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dj
  namespace: appmesh-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dj
      version: v1
  template:
    metadata:
      annotations:
        appmesh.k8s.aws/mesh: appmesh-demo
      labels:
        app: dj
        version: v1
    spec:
      containers:
        - name: dj
          image: "curlimages/curl"
          ports:
            - containerPort: 9080
          command:
            - sleep
            - "3600"
